### ISSUE TITLE
`chr': 488 out of char range (RangeError)

### ISSUE THREAD

**Issue by noplanman** [rubysolo/qrio#3]
Even though this project seems abandoned, I'll try to see if you can help me out.

On one of the QR codes I have I get the following error message:
```
/home/.rvm/gems/ruby-2.2.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:209:in `chr': 488 out of char range (RangeError)
  from /home/.rvm/gems/ruby-2.2.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:209:in `block in text'
  from /home/.rvm/gems/ruby-2.2.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:207:in `times'
  from /home/.rvm/gems/ruby-2.2.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:207:in `text'
  from /usr/local/bin/otp:52:in `<main>'
```

After searching online in vain, I have no idea what to do.

Also, this is the only gem I found to decode QR codes. Do you know of any actively developed ones?

**Comment by rubysolo** [comment]
I don't know of any actively maintained ruby QR decoders, sorry.  Can you share the image with me?  I might be able to track down where it is failing.  If you don't want to attach it here, my email is my github username at gmail.

**Comment by noplanman** [comment]
Thanks a lot, have sent you an email 👍

**Comment by MaicolBen** [comment]
@noplanman did you find any solution to this?

**Comment by noplanman** [comment]
@MaicolBen Unfortunately not.

I decided to remove the decode feature from one of my projects, or rather: leave it as "if it works yay, otherwise :shrug:"
