### ISSUE TITLE
"unknown mode" issue

### ISSUE THREAD

**Issue by jathayde** [rubysolo/qrio#4]
Running a complex test image but getting error codes (mode 11). Ruby 2.2.5 

```
irb(main):001:0> require 'qrio'
=> true
irb(main):002:0> puts Qrio::Qr.load("258atest.png").qr.text
RuntimeError: Unknown mode 11
	from /Users/jathayde/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:312:in `set_mode'
	from /Users/jathayde/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:203:in `text'
	from (irb):2
	from /Users/jathayde/.rbenv/versions/2.2.5/bin/irb:11:in `<main>'
```

Attached the failing image. Another image failed with mode 10 (alphanumeric?).

![258atest](https://user-images.githubusercontent.com/2223/26976013-28c0a096-4cf0-11e7-953d-9fa59146d570.png)

**Comment by noraj** [comment]
I have the same issue with an image only containing a pure valid qr code:

```
RuntimeError: Unknown mode 10
	from /home/noraj/.rvm/gems/ruby-2.4.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:312:in `set_mode'
	from /home/noraj/.rvm/gems/ruby-2.4.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:203:in `text'
	from (irb):5
	from /home/noraj/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
```
