### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by bverem** [rubysolo/qrio#6]
When loading a QR-containing PNG with text (which can be read by any webcam QR reader), I get an "incompatible character encodings: ASCII-8BIT and UTF-8" error when trying to get the text through ```qr = Qrio::Qr.load("something.png").qr.text```. I can't quite tell what the issue is. How might I address this issue? Thanks!

```
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:212:in `join'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/qrio-0.0.1/lib/qrio/qr_matrix.rb:212:in `text'
```

EDIT: It appears that Qrio has issues decoding strings containing a space near other symbols (such as colons and commas) and a space next to each other. I believe that it's a Qrio issue because other QR readers have no issues with this string. Advice would be sincerely appreciated!

EDIT 2: Also, hyphens (even without spaces).

**Comment by bverem** [comment]
It seems that this gem is no longer supported, and further testing seems to indicate that, for the most part, the gem doesn't reliably convert even simple QR codes (i.e., those consisting of a single number). I may fork it sometime in the next few months once my current project is completed. If anybody managed to address these issues, I'd be happy to hear your solutions!

**Comment by hasandiwan** [comment]
How's the fork coming along, @bverem ? 

I'm running into this same error with the qr code for https://i.ibb.co/XCfRYYd/image.png because the text contains an emoji.

**Comment by bverem** [comment]
Apologies--I started using [zbar](https://github.com/willglynn/ruby-zbar) instead.
